name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: build
      run: dotnet build --configuration Release
    - name: test
      run: dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover NUnit2XUnit.Tests
